language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
  
matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 7.0
    - php: nightly
    - php: hhvm
  
install:
  - composer install
  
script:
  - ./vendor/bin/phpunit
